name: Mergebot

on:
  workflow_run:
    workflows:
      - Pull request
    types:
      - completed
  workflow_dispatch:
  
jobs:
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:    
     - name: Checkout private repo
       uses: e-conomic/mergebot@v1
       with:
          github_app_id: ${{ secrets.APP_ID}}
          github_app_private_key: ${{ secrets.PRIVATE_KEY }}    
          github_app_installation_id: ${{ secrets.INSTALLATION_ID }}
