name: Pull request

on: 
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3     
